"""
Alert Model for CMS Service.

Tracks system alerts including NCMEC matches, device offline events,
errors, and software updates.
"""

from datetime import datetime, timezone
import uuid

from cms.models import db, DateTimeUTC


class Alert(db.Model):
    """
    SQLAlchemy model representing a system alert.

    Alerts are generated by devices or the system for various events
    including NCMEC face matches, device offline events, errors, and updates.

    Attributes:
        id: Unique auto-increment identifier
        device_id: Device identifier (may be null for system-level alerts)
        hub_id: Hub identifier if related to a hub
        network_id: Network identifier
        store_name: Human-readable store name
        alert_type: Type of alert (ncmec, offline, error, update)
        severity: Alert severity (info, warning, critical)
        message: Human-readable alert message
        data_json: JSON blob with additional alert data
        acknowledged: Whether the alert has been acknowledged
        acknowledged_by: Who acknowledged the alert
        created_at: When the alert was created
    """

    __tablename__ = 'alerts'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    device_id = db.Column(db.String(100), index=True, nullable=True)
    hub_id = db.Column(db.String(100), nullable=True)
    network_id = db.Column(db.String(100), nullable=True)
    store_name = db.Column(db.String(200), nullable=True)
    alert_type = db.Column(db.String(50), nullable=False, index=True)
    severity = db.Column(db.String(20), default='info')
    message = db.Column(db.Text, nullable=True)
    data_json = db.Column(db.Text, nullable=True)
    acknowledged = db.Column(db.Boolean, default=False)
    acknowledged_by = db.Column(db.String(100), nullable=True)
    created_at = db.Column(DateTimeUTC(), default=lambda: datetime.now(timezone.utc), index=True)

    def to_dict(self):
        """Serialize the alert to a dictionary for API responses."""
        return {
            'id': self.id,
            'device_id': self.device_id,
            'hub_id': self.hub_id,
            'network_id': self.network_id,
            'store_name': self.store_name,
            'alert_type': self.alert_type,
            'severity': self.severity,
            'message': self.message,
            'data_json': self.data_json,
            'acknowledged': self.acknowledged,
            'acknowledged_by': self.acknowledged_by,
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f'<Alert {self.alert_type} - {self.severity} - {self.device_id}>'
