"""Add sync tracking fields and device sync tables

Revision ID: 34d9f195e29d
Revises: 
Create Date: 2026-01-20 15:52:11.312439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d9f195e29d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))
        batch_op.create_index(batch_op.f('ix_content_catalog_asset_uuid'), ['catalog_asset_uuid'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('pairing_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'screen_layouts', ['layout_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'folders', ['parent_id'], ['id'])

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('screen_layers', schema=None) as batch_op:
        batch_op.alter_column('content_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'none'"))
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('synced_content', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('synced_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('screen_layers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'])
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('content_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'none'"))

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('version')
        batch_op.drop_column('sync_status')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'screen_layouts', ['layout_id'], ['id'])
        batch_op.alter_column('pairing_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_catalog_asset_uuid'))
        batch_op.alter_column('source',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))

    # ### end Alembic commands ###
